class CreateRankings < ActiveRecord::Migration
	def self.up
    	execute <<-SQL
        CREATE VIEW `rankings` AS select `championship_teams`.`championship_id` AS `championship_id`,`championship_teams`.`team_id` AS `team_id`,`championship_teams`.`team_name` AS `team_name`,(((select count(`win_lose`.`winner_id`) from `win_lose` where ((`championship_teams`.`team_id` = `win_lose`.`winner_id`) and (not(`win_lose`.`is_equal`)) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) * 2) + (select count(`win_lose`.`looser_id`) from `win_lose` where (((`championship_teams`.`team_id` = `win_lose`.`looser_id`) or (`championship_teams`.`team_id` = `win_lose`.`winner_id`)) and `win_lose`.`is_equal` and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`)))) AS `score`,(select count(`win_lose`.`winner_id`) from `win_lose` where ((`championship_teams`.`team_id` = `win_lose`.`winner_id`) and (not(`win_lose`.`is_equal`)) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) AS `win`,(select count(`win_lose`.`looser_id`) from `win_lose` where (((`championship_teams`.`team_id` = `win_lose`.`looser_id`) or (`championship_teams`.`team_id` = `win_lose`.`winner_id`)) and `win_lose`.`is_equal` and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) AS `equal`,(select count(`win_lose`.`looser_id`) from `win_lose` where ((`championship_teams`.`team_id` = `win_lose`.`looser_id`) and (not(`win_lose`.`is_equal`)) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) AS `lose`,(select sum(`win_lose`.`winner_score`) from `win_lose` where (((`championship_teams`.`team_id` = `win_lose`.`winner_id`) or (`win_lose`.`is_equal` and (`championship_teams`.`team_id` = `win_lose`.`looser_id`))) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) AS `goals_scored`,(select sum(`win_lose`.`looser_score`) from `win_lose` where (((`championship_teams`.`team_id` = `win_lose`.`looser_id`) or (`win_lose`.`is_equal` and (`championship_teams`.`team_id` = `win_lose`.`winner_id`))) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) AS `let_in_goals` from `championship_teams` order by (((select count(`win_lose`.`winner_id`) from `win_lose` where ((`championship_teams`.`team_id` = `win_lose`.`winner_id`) and (not(`win_lose`.`is_equal`)) and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`))) * 2) + (select count(`win_lose`.`looser_id`) from `win_lose` where (((`championship_teams`.`team_id` = `win_lose`.`looser_id`) or (`championship_teams`.`team_id` = `win_lose`.`winner_id`)) and `win_lose`.`is_equal` and (`win_lose`.`championship_id` = `championship_teams`.`championship_id`)))) desc
      SQL
  	end
  	def self.down
    	execute <<-SQL
      		DROP VIEW `rankings`
    	SQL
  	end
end
