require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ChampionshipsController do

  def mock_championship(stubs={})
    @mock_championship ||= mock_model(Championship, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all championships as @championships" do
      Championship.stub(:all) { [mock_championship] }
      get :index
      assigns(:championships).should eq([mock_championship])
    end
  end

  describe "GET show" do
    it "assigns the requested championship as @championship" do
      Championship.stub(:find).with("37") { mock_championship }
      get :show, :id => "37"
      assigns(:championship).should be(mock_championship)
    end
  end

  describe "GET new" do
    it "assigns a new championship as @championship" do
      Championship.stub(:new) { mock_championship }
      get :new
      assigns(:championship).should be(mock_championship)
    end
  end

  describe "GET edit" do
    it "assigns the requested championship as @championship" do
      Championship.stub(:find).with("37") { mock_championship }
      get :edit, :id => "37"
      assigns(:championship).should be(mock_championship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created championship as @championship" do
        Championship.stub(:new).with({'these' => 'params'}) { mock_championship(:save => true) }
        post :create, :championship => {'these' => 'params'}
        assigns(:championship).should be(mock_championship)
      end

      it "redirects to the created championship" do
        Championship.stub(:new) { mock_championship(:save => true) }
        post :create, :championship => {}
        response.should redirect_to(championship_url(mock_championship))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved championship as @championship" do
        Championship.stub(:new).with({'these' => 'params'}) { mock_championship(:save => false) }
        post :create, :championship => {'these' => 'params'}
        assigns(:championship).should be(mock_championship)
      end

      it "re-renders the 'new' template" do
        Championship.stub(:new) { mock_championship(:save => false) }
        post :create, :championship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested championship" do
        Championship.stub(:find).with("37") { mock_championship }
        mock_championship.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :championship => {'these' => 'params'}
      end

      it "assigns the requested championship as @championship" do
        Championship.stub(:find) { mock_championship(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:championship).should be(mock_championship)
      end

      it "redirects to the championship" do
        Championship.stub(:find) { mock_championship(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(championship_url(mock_championship))
      end
    end

    describe "with invalid params" do
      it "assigns the championship as @championship" do
        Championship.stub(:find) { mock_championship(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:championship).should be(mock_championship)
      end

      it "re-renders the 'edit' template" do
        Championship.stub(:find) { mock_championship(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested championship" do
      Championship.stub(:find).with("37") { mock_championship }
      mock_championship.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the championships list" do
      Championship.stub(:find) { mock_championship }
      delete :destroy, :id => "1"
      response.should redirect_to(championships_url)
    end
  end

end
