require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FactsController do

  def mock_fact(stubs={})
    @mock_fact ||= mock_model(Fact, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all facts as @facts" do
      Fact.stub(:all) { [mock_fact] }
      get :index
      assigns(:facts).should eq([mock_fact])
    end
  end

  describe "GET show" do
    it "assigns the requested fact as @fact" do
      Fact.stub(:find).with("37") { mock_fact }
      get :show, :id => "37"
      assigns(:fact).should be(mock_fact)
    end
  end

  describe "GET new" do
    it "assigns a new fact as @fact" do
      Fact.stub(:new) { mock_fact }
      get :new
      assigns(:fact).should be(mock_fact)
    end
  end

  describe "GET edit" do
    it "assigns the requested fact as @fact" do
      Fact.stub(:find).with("37") { mock_fact }
      get :edit, :id => "37"
      assigns(:fact).should be(mock_fact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created fact as @fact" do
        Fact.stub(:new).with({'these' => 'params'}) { mock_fact(:save => true) }
        post :create, :fact => {'these' => 'params'}
        assigns(:fact).should be(mock_fact)
      end

      it "redirects to the created fact" do
        Fact.stub(:new) { mock_fact(:save => true) }
        post :create, :fact => {}
        response.should redirect_to(fact_url(mock_fact))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fact as @fact" do
        Fact.stub(:new).with({'these' => 'params'}) { mock_fact(:save => false) }
        post :create, :fact => {'these' => 'params'}
        assigns(:fact).should be(mock_fact)
      end

      it "re-renders the 'new' template" do
        Fact.stub(:new) { mock_fact(:save => false) }
        post :create, :fact => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fact" do
        Fact.stub(:find).with("37") { mock_fact }
        mock_fact.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :fact => {'these' => 'params'}
      end

      it "assigns the requested fact as @fact" do
        Fact.stub(:find) { mock_fact(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:fact).should be(mock_fact)
      end

      it "redirects to the fact" do
        Fact.stub(:find) { mock_fact(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(fact_url(mock_fact))
      end
    end

    describe "with invalid params" do
      it "assigns the fact as @fact" do
        Fact.stub(:find) { mock_fact(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:fact).should be(mock_fact)
      end

      it "re-renders the 'edit' template" do
        Fact.stub(:find) { mock_fact(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fact" do
      Fact.stub(:find).with("37") { mock_fact }
      mock_fact.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the facts list" do
      Fact.stub(:find) { mock_fact }
      delete :destroy, :id => "1"
      response.should redirect_to(facts_url)
    end
  end

end
