require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe GymsController do

  def mock_gym(stubs={})
    @mock_gym ||= mock_model(Gym, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all gyms as @gyms" do
      Gym.stub(:all) { [mock_gym] }
      get :index
      assigns(:gyms).should eq([mock_gym])
    end
  end

  describe "GET show" do
    it "assigns the requested gym as @gym" do
      Gym.stub(:find).with("37") { mock_gym }
      get :show, :id => "37"
      assigns(:gym).should be(mock_gym)
    end
  end

  describe "GET new" do
    it "assigns a new gym as @gym" do
      Gym.stub(:new) { mock_gym }
      get :new
      assigns(:gym).should be(mock_gym)
    end
  end

  describe "GET edit" do
    it "assigns the requested gym as @gym" do
      Gym.stub(:find).with("37") { mock_gym }
      get :edit, :id => "37"
      assigns(:gym).should be(mock_gym)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created gym as @gym" do
        Gym.stub(:new).with({'these' => 'params'}) { mock_gym(:save => true) }
        post :create, :gym => {'these' => 'params'}
        assigns(:gym).should be(mock_gym)
      end

      it "redirects to the created gym" do
        Gym.stub(:new) { mock_gym(:save => true) }
        post :create, :gym => {}
        response.should redirect_to(gym_url(mock_gym))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gym as @gym" do
        Gym.stub(:new).with({'these' => 'params'}) { mock_gym(:save => false) }
        post :create, :gym => {'these' => 'params'}
        assigns(:gym).should be(mock_gym)
      end

      it "re-renders the 'new' template" do
        Gym.stub(:new) { mock_gym(:save => false) }
        post :create, :gym => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gym" do
        Gym.stub(:find).with("37") { mock_gym }
        mock_gym.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :gym => {'these' => 'params'}
      end

      it "assigns the requested gym as @gym" do
        Gym.stub(:find) { mock_gym(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:gym).should be(mock_gym)
      end

      it "redirects to the gym" do
        Gym.stub(:find) { mock_gym(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(gym_url(mock_gym))
      end
    end

    describe "with invalid params" do
      it "assigns the gym as @gym" do
        Gym.stub(:find) { mock_gym(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:gym).should be(mock_gym)
      end

      it "re-renders the 'edit' template" do
        Gym.stub(:find) { mock_gym(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gym" do
      Gym.stub(:find).with("37") { mock_gym }
      mock_gym.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the gyms list" do
      Gym.stub(:find) { mock_gym }
      delete :destroy, :id => "1"
      response.should redirect_to(gyms_url)
    end
  end

end
